import { useEffect, useMemo, useState } from 'react'
import './Portfolio.css'

const sections = [
	{ id: 'about', label: 'About me', icon: '01', color: '#69d4ff', eyebrow: 'ORIGIN STORY', title: 'Curious by default.', description: 'I am Nikash, a B.Tech student and developer who turns complex ideas into clear, playful digital experiences.', details: ['React developer', 'Problem solver', 'Creative thinker'], accent: 'cyan' },
	{ id: 'education', label: 'Education', icon: '02', color: '#b49cff', eyebrow: 'THE FOUNDATION', title: 'Building from first principles.', description: 'My academic journey blends application development, data structures, databases, and a steady curiosity for what happens beneath the interface.', details: ['B.Tech AIDS', 'Data structures', 'Web development'], accent: 'violet' },
	{ id: 'skills', label: 'Technical skills', icon: '03', color: '#7de28b', eyebrow: 'THE TOOLKIT', title: 'A practical stack with room to grow.', description: 'I like tools that make ideas easier to test, explain, and ship. These are the technologies I reach for most often.', details: ['React + Vite', 'JavaScript', 'Python + SQL'], accent: 'green', skills: [['React', 85], ['JavaScript', 80], ['HTML & CSS', 90], ['Python', 70]] },
	{ id: 'projects', label: 'Projects', icon: '04', color: '#ffc766', eyebrow: 'THE WORKSHOP', title: 'Small systems, real outcomes.', description: 'A selection of experiments and products that helped me learn by making the interface, the logic, and the edge cases work together.', details: ['Attendance tracker', 'Student management', 'Data analysis tools'], accent: 'amber' },
	{ id: 'security', label: 'Security interests', icon: '05', color: '#ff8f96', eyebrow: 'THE WATCHTOWER', title: 'Designing with trust in mind.', description: 'Secure coding is part of good product thinking: protect the data, respect the user, and make the safe path the easy path.', details: ['Web security', 'Authentication', 'Data protection'], accent: 'coral' },
	{ id: 'contact', label: 'Contact', icon: '06', color: '#ff9fce', eyebrow: 'THE ROOFTOP', title: 'Let’s build the next floor.', description: 'Have a project, a question, or a good problem to untangle? The best way to reach me is through one of these channels.', details: ['Email', 'GitHub', 'LinkedIn'], accent: 'pink' },
]
const achievements = [['first', 'First floor', 'Start the city'], ['builder', 'City builder', 'Reach floor 3'], ['combo', 'Combo master', 'Build three in a row'], ['master', 'Portfolio master', 'Complete every floor']]

function Stat({ value, label }) { return <div className="stat"><strong>{value}</strong><span>{label}</span></div> }

function Portfolio() {
	const [built, setBuilt] = useState([]); const [lives, setLives] = useState(3); const [score, setScore] = useState(0); const [combo, setCombo] = useState(0); const [paused, setPaused] = useState(false); const [night, setNight] = useState(false); const [selected, setSelected] = useState(null); const [notice, setNotice] = useState('Place the next floor to unlock the city.'); const [earned, setEarned] = useState([])
	const next = sections[built.length]; const coins = Math.floor(score / 25); const progress = Math.round((built.length / sections.length) * 100); const canBuild = Boolean(next) && lives > 0 && !paused; const activeFloor = useMemo(() => built.length, [built.length])
	const earn = (id) => setEarned((current) => current.includes(id) ? current : [...current, id])
	const buildFloor = () => {
		if (!canBuild) return
		if (Math.random() <= .16) { const remaining = lives - 1; setLives(remaining); setCombo(0); setNotice(remaining ? 'The alignment slipped. Try the next drop.' : 'The city needs a reset. Rebuild when ready.'); return }
		const nextCombo = combo + 1; setBuilt((current) => [...current, next]); setCombo(nextCombo); setScore((current) => current + 100 + nextCombo * 25); setNotice(next.id === 'contact' ? 'The skyline is complete. Your portfolio is open.' : `${next.label} unlocked. Keep building.`); if (built.length === 0) earn('first'); if (built.length === 2) earn('builder'); if (nextCombo >= 3) earn('combo'); if (built.length === sections.length - 1) earn('master')
	}
	const reset = () => { setBuilt([]); setLives(3); setScore(0); setCombo(0); setPaused(false); setSelected(null); setEarned([]); setNotice('Place the next floor to unlock the city.') }
	useEffect(() => { const onKeyDown = (event) => { if (event.code === 'Space') { event.preventDefault(); buildFloor() } if (event.code === 'KeyP') setPaused((value) => !value); if (event.code === 'KeyR') reset(); if (event.code === 'Escape') setSelected(null) }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown) })
	return <main className={`portfolio-app ${night ? 'is-night' : ''}`}>
		<header className="topbar"><div className="brand"><span className="brand-mark">✦</span><div><strong>CITY / BLOXX</strong><small>PORTFOLIO 01</small></div></div><div className="status"><span className="live-dot" /> LIVE BUILD <i>•</i> 2026 EDITION</div><nav className="top-actions" aria-label="Game controls"><button onClick={() => setNight((value) => !value)} aria-label="Toggle day and night mode">{night ? '☀' : '☾'}</button><button onClick={() => setPaused((value) => !value)} aria-label={paused ? 'Resume game' : 'Pause game'}>{paused ? '▶' : 'Ⅱ'}</button><button onClick={reset} aria-label="Restart game">↻</button></nav></header>
		<section className="intro"><div><p className="kicker">INTERACTIVE PORTFOLIO / 411625243035</p><h1>Build the <em>story.</em><br />Explore the city.</h1><p className="intro-copy">Every floor unlocks a little more of how I think, learn, and make. Stack the skyline, then step inside.</p></div><div className="intro-meta"><span>SCROLL TO EXPLORE</span><span className="arrow">↓</span></div></section>
		<section className="game-shell" aria-label="City building game"><div className="skyline-label"><span>SKYLINE / {String(activeFloor).padStart(2, '0')}</span><span>{progress}% COMPLETE</span></div><div className="sky"><div className="sun" /><div className="moon" /><div className="cloud cloud-one" /><div className="cloud cloud-two" /><div className="city-grid" /><div className="side-tower tower-left"><i /><i /><i /><i /></div><div className="side-tower tower-right"><i /><i /><i /></div><div className="tower"><div className="tower-cap">NKR / 01</div>{built.map((floor) => <button key={floor.id} className={`floor floor-${floor.accent}`} onClick={() => setSelected(floor)} style={{ '--floor-color': floor.color }}><span className="floor-number">{floor.icon}</span><span><b>{floor.label}</b><small>CLICK TO OPEN</small></span><span className="floor-lights"><i /><i /><i /></span></button>)}{next && <div className="falling-floor" style={{ '--floor-color': next.color }}><span>{next.icon}</span><b>{next.label}</b><small>READY TO PLACE</small></div>}</div><div className="road"><div className="lane-markings" /><span className="car car-a">▰</span><span className="car car-b">▰</span></div></div><div className="game-footer"><p className="game-notice"><span className="signal">●</span>{notice}</p><div className="build-row"><button className="build-button" onClick={buildFloor} disabled={!canBuild}>{next ? `BUILD ${next.icon} / ${next.label.toUpperCase()}` : 'CITY COMPLETE'}</button><span className="shortcut">SPACE <i>to build</i></span></div><div className="lives">{[0, 1, 2].map((life) => <span key={life} className={life < lives ? 'on' : ''}>♥</span>)}</div></div></section>
		<section className="dashboard"><div className="stats-panel"><p className="section-label">BUILD METRICS</p><div className="stats-grid"><Stat value={score.toString().padStart(4, '0')} label="SCORE" /><Stat value={coins.toString().padStart(2, '0')} label="COINS" /><Stat value={`x${combo}`} label="COMBO" /><Stat value={`${built.length}/${sections.length}`} label="FLOORS" /></div><div className="progress-line"><span style={{ width: `${progress}%` }} /></div><div className="progress-caption"><span>CITY PROGRESS</span><b>{progress}%</b></div></div><div className="achievements"><div className="section-heading"><p className="section-label">ACHIEVEMENTS</p><span>{earned.length}/{achievements.length}</span></div>{achievements.map(([id, title, caption]) => <div className={`achievement ${earned.includes(id) ? 'earned' : ''}`} key={id}><span className="achievement-icon">{earned.includes(id) ? '✓' : '·'}</span><div><b>{title}</b><small>{caption}</small></div></div>)}</div><div className="controls-note"><p className="section-label">HOW TO PLAY</p><p><kbd>SPACE</kbd> Build floor <kbd>P</kbd> Pause <kbd>R</kbd> Restart</p><p className="muted">Click any completed floor to explore the portfolio.</p></div></section>
		{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><article className={`portfolio-modal modal-${selected.accent}`} onClick={(event) => event.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} aria-label="Close portfolio section">×</button><div className="modal-top"><span>{selected.icon}</span><p>{selected.eyebrow}</p></div><h2>{selected.title}</h2><p className="modal-description">{selected.description}</p><div className="detail-list">{selected.details.map((detail) => <span key={detail}>↳ {detail}</span>)}</div>{selected.skills && <div className="skill-list">{selected.skills.map(([skill, value]) => <div key={skill}><div><span>{skill}</span><b>{value}%</b></div><div className="skill-track"><i style={{ width: `${value}%` }} /></div></div>)}</div>}{selected.id === 'contact' && <div className="contact-links"><a href="mailto:nikash@example.com">Email me ↗</a><a href="https://github.com" target="_blank" rel="noreferrer">GitHub ↗</a><a href="https://linkedin.com" target="_blank" rel="noreferrer">LinkedIn ↗</a></div>}<div className="modal-footer"><span>FLOOR {selected.icon} / CITY BLOXX</span><button onClick={() => setSelected(null)}>BACK TO CITY</button></div></article></div>}
	</main>
}

export default Portfolio
