const courses = [
	{ code: 'AI402', title: 'Artificial Intelligence', instructor: 'Dr. Ananya Rao', progress: 78, grade: 'A', color: 'mint', initials: 'AI' },
	{ code: 'AI406', title: 'Machine Learning', instructor: 'Prof. R. Karthik', progress: 64, grade: 'A-', color: 'coral', initials: 'ML' },
	{ code: 'DS410', title: 'Data Science', instructor: 'Dr. Meera Iyer', progress: 91, grade: 'A+', color: 'blue', initials: 'DS' },
	{ code: 'AI414', title: 'Python Programming', instructor: 'Prof. Vivek Nair', progress: 52, grade: 'B+', color: 'yellow', initials: 'PY' },
]

const schedule = [
	{ time: '09:00', course: 'Artificial Intelligence', code: 'AI402', room: 'Lab 2', color: 'mint', end: '10:30 AM' },
	{ time: '11:15', course: 'Machine Learning', code: 'AI406', room: 'Room 310', color: 'coral', end: '12:45 PM' },
	{ time: '14:00', course: 'Data Science', code: 'DS410', room: 'Lab 1', color: 'blue', end: '03:30 PM' },
]

const gradeItems = [
	{ course: 'Data Science', code: 'DS410', grade: 'A+', score: '96 / 100', color: 'blue' },
	{ course: 'Artificial Intelligence', code: 'AI402', grade: 'A', score: '91 / 100', color: 'mint' },
	{ course: 'Machine Learning', code: 'AI406', grade: 'A-', score: '88 / 100', color: 'coral' },
	{ course: 'Python Programming', code: 'AI414', grade: 'B+', score: '84 / 100', color: 'yellow' },
]

const navigation = ['Overview', 'Courses', 'Grades', 'Schedule']
const state = { view: 'Overview', query: '', profileOpen: false, mobileNavOpen: false }
const app = document.querySelector('#app')

const eyebrow = (text, live = false) => `<span class="eyebrow">${live ? '<span class="live-dot"></span>' : ''}${text}</span>`
const courseRow = (course) => `<article class="course-row"><div class="course-mark ${course.color}">${course.initials}</div><div class="course-info"><span class="course-code">${course.code}</span><h3>${course.title}</h3><p>${course.instructor}</p></div><div class="course-progress"><div class="progress-label"><span>Course progress</span><strong>${course.progress}%</strong></div><div class="progress-track" role="progressbar" aria-label="${course.title} progress" aria-valuenow="${course.progress}" aria-valuemin="0" aria-valuemax="100"><span style="width:${course.progress}%"></span></div></div><span class="grade-pill ${course.color}">${course.grade}</span></article>`
function filteredCourses() { const query = state.query.trim().toLowerCase(); return courses.filter((course) => `${course.title} ${course.code} ${course.instructor}`.toLowerCase().includes(query)) }
function emptyState() { return `<p class="empty-state">No results match “${state.query}”. Try another search.</p>` }

function overview() {
	const visibleCourses = filteredCourses()
	return `<section class="welcome-band"><div class="welcome-copy">${eyebrow('MONDAY, 16 FEBRUARY 2026', true)}<h1>A good day to<br><em>make progress.</em></h1><p>Your semester is moving along nicely. Here’s what’s happening with your studies.</p><button class="text-action" data-view="Courses">Explore your courses <span>↗</span></button></div><div class="welcome-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="art-sun"></div><div class="art-book"><span></span><span></span><span></span></div><span class="art-star star-one">✳</span><span class="art-star star-two">✳</span><div class="art-caption">LEARN<br>WITH INTENT</div></div><div class="welcome-index"><span>01</span><i></i></div></section><section class="stats-strip"><div class="stat-item"><span class="stat-label">CURRENT GPA</span><strong>3.82<span>/4.0</span></strong><small><i class="stat-up">↗</i> 0.14 this semester</small></div><div class="stat-item"><span class="stat-label">CREDITS EARNED</span><strong>68<span> / 120</span></strong><small>52 credits to graduation</small></div><div class="stat-item"><span class="stat-label">ATTENDANCE</span><strong>94<span>%</span></strong><small>Across all enrolled courses</small></div><div class="stat-item stat-next"><span class="stat-label">NEXT CLASS</span><strong>09:00<span> AM</span></strong><small>Artificial Intelligence · Lab 2</small></div></section><div class="section-heading"><div>${eyebrow('YOUR LEARNING')}<h2>In progress <span>04</span></h2></div><button class="subtle-link" data-view="Courses">All courses <span>↗</span></button></div><section class="course-list">${visibleCourses.slice(0, 3).map(courseRow).join('') || emptyState()}</section><div class="overview-bottom"><section class="schedule-preview"><div class="mini-section-heading"><div>${eyebrow('MONDAY · 16 FEB')}<h2>Today’s schedule</h2></div><button class="round-link" aria-label="View full schedule" data-view="Schedule">↗</button></div>${schedule.slice(0, 2).map((item) => `<div class="schedule-line"><time>${item.time}</time><span class="schedule-dot ${item.color}"></span><div><strong>${item.course}</strong><small>${item.room} · ${item.code}</small></div></div>`).join('')}<button class="schedule-more" data-view="Schedule">View weekly schedule <span>→</span></button></section><section class="focus-note">${eyebrow('A NOTE FOR YOU')}<span class="focus-mark">“</span><blockquote>Small, consistent steps add up to remarkable things.</blockquote><p>Keep showing up. You’re doing better than you think.</p><span class="focus-signature">YOUR NORTHSTAR TEAM</span></section></div>`
}

function pageView() {
	if (state.view === 'Overview') return overview()
	if (state.view === 'Courses') return `<section class="page-section"><div class="page-title">${eyebrow('SEMESTER 04 · 2025 / 26')}<h1>Your courses<span class="title-period">.</span></h1><p>Four courses, one semester at a time.</p></div><div class="section-heading"><div>${eyebrow('ENROLLED SUBJECTS')}<h2>Course overview <span>${String(filteredCourses().length).padStart(2, '0')}</span></h2></div><span class="term-chip">FEB — JUN 2026</span></div><section class="course-list course-list-full">${filteredCourses().map(courseRow).join('') || emptyState()}</section></section>`
	if (state.view === 'Grades') return `<section class="page-section"><div class="page-title">${eyebrow('YOUR ACADEMIC RECORD')}<h1>Grades &amp; results<span class="title-period">.</span></h1><p>A clear picture of how far you’ve come.</p></div><div class="grade-summary">${eyebrow('CUMULATIVE GPA')}<strong>3.82<span> / 4.00</span></strong><div class="grade-summary-foot"><span class="stat-up">↗</span> Up 0.14 points this semester</div><div class="grade-decoration">A</div></div><div class="section-heading"><div>${eyebrow('SEMESTER 04')}<h2>Latest results <span>04</span></h2></div><span class="term-chip">UPDATED 12 FEB</span></div><section class="grade-list">${gradeItems.filter((item) => `${item.course} ${item.code} ${item.grade}`.toLowerCase().includes(state.query.toLowerCase().trim())).map((item) => `<article class="grade-row"><div class="course-mark ${item.color}">${item.code.slice(2)}</div><div class="grade-course"><h3>${item.course}</h3><span>${item.code}</span></div><span class="grade-score">${item.score}</span><strong class="grade-pill ${item.color}">${item.grade}</strong></article>`).join('') || emptyState()}</section></section>`
	return `<section class="page-section"><div class="page-title">${eyebrow('WEEK 07 · SEMESTER 04')}<h1>Class schedule<span class="title-period">.</span></h1><p>Your week, thoughtfully laid out.</p></div><div class="schedule-datebar"><div>${eyebrow('MONDAY')}<strong>16 <span>FEBRUARY 2026</span></strong></div><span class="term-chip">3 CLASSES TODAY</span></div><section class="full-schedule">${schedule.map((item) => `<article class="full-schedule-row"><time><strong>${item.time}</strong><span>${item.end}</span></time><span class="schedule-rail ${item.color}"></span><div class="schedule-card ${item.color}">${eyebrow(`${item.code} · LECTURE`)}<h2>${item.course}</h2><p>AI &amp; Data Science · ${item.room}</p><span class="schedule-card-arrow">↗</span></div></article>`).join('')}</section></section>`
}

function render() {
	app.innerHTML = `<div class="portal-shell"><aside class="sidebar ${state.mobileNavOpen ? 'sidebar-open' : ''}"><a class="brand" href="#overview" data-view="Overview"><span class="brand-symbol"><i></i><i></i><i></i><i></i></span><span class="brand-name">northstar<span>STUDENT PORTAL</span></span></a><div class="sidebar-label">CAMPUS</div><nav class="side-nav">${navigation.map((item, index) => `<button class="nav-item ${state.view === item ? 'nav-active' : ''}" data-view="${item}" aria-current="${state.view === item ? 'page' : 'false'}"><span class="nav-index">0${index + 1}</span><span>${item}</span>${item === 'Courses' ? '<span class="nav-count">04</span>' : ''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="semester-note"><span class="live-dot"></span> FALL SEMESTER <strong>2025 / 26</strong></div><div class="sidebar-student"><div class="avatar avatar-small">NK</div><div><strong>Nikash K R</strong><span>AI &amp; Data Science</span></div><span class="sidebar-chevron">↗</span></div></div></aside><main class="portal-main"><header class="topbar"><button class="menu-toggle" aria-label="${state.mobileNavOpen ? 'Close navigation' : 'Open navigation'}" aria-expanded="${state.mobileNavOpen}"><span></span><span></span></button><div class="breadcrumb"><span>STUDENT SPACE</span><b>/</b><strong>${state.view}</strong></div><div class="topbar-actions"><label class="search-box"><span>⌕</span><input type="search" aria-label="Search courses" placeholder="Find a course..." value="${state.query.replace(/"/g, '&quot;')}"><kbd>/</kbd></label><button class="profile-trigger" aria-expanded="${state.profileOpen}"><span class="avatar">NK</span><span class="profile-trigger-label">My profile</span><span>⌄</span></button></div></header>${state.profileOpen ? `<section class="profile-panel"><div class="profile-panel-heading"><div class="avatar avatar-large">NK</div><div>${eyebrow('STUDENT PROFILE')}<h2>Nikash K R</h2></div></div><dl class="profile-details"><div><dt>Roll number</dt><dd>CB101</dd></div><div><dt>Department</dt><dd>AI &amp; Data Science</dd></div><div><dt>Year</dt><dd>II Year</dd></div><div><dt>Email</dt><dd><a href="mailto:nikash@example.com">nikash@example.com</a></dd></div></dl></section>` : ''}<div class="page-content">${pageView()}<footer class="page-footer"><span>© 2026 NORTHSTAR CAMPUS</span><span>MADE FOR YOUR NEXT STEP <i>✳</i></span></footer></div></main>${state.mobileNavOpen ? '<button class="nav-scrim" aria-label="Close navigation"></button>' : ''}</div>`
	bindEvents()
}

function bindEvents() {
	app.querySelectorAll('[data-view]').forEach((element) => element.addEventListener('click', (event) => { event.preventDefault(); state.view = element.dataset.view; state.mobileNavOpen = false; render() }))
	app.querySelector('.menu-toggle')?.addEventListener('click', () => { state.mobileNavOpen = !state.mobileNavOpen; render() })
	app.querySelector('.nav-scrim')?.addEventListener('click', () => { state.mobileNavOpen = false; render() })
	app.querySelector('.profile-trigger')?.addEventListener('click', () => { state.profileOpen = !state.profileOpen; render() })
	app.querySelector('.search-box input')?.addEventListener('input', (event) => { state.query = event.target.value; render(); const input = app.querySelector('.search-box input'); input.focus(); input.setSelectionRange(input.value.length, input.value.length) })
}

document.addEventListener('keydown', (event) => { if (event.key === '/' && document.activeElement.tagName !== 'INPUT') { event.preventDefault(); app.querySelector('.search-box input')?.focus() } })
render()
